INFO 2025-02-01 16:08:56,133 autoreload 20680 28596 Watching for file changes with StatReloader
INFO 2025-02-01 16:09:09,842 basehttp 20680 9248 "GET / HTTP/1.1" 200 1633
INFO 2025-02-01 16:09:10,034 basehttp 20680 9248 "GET /?format=openapi HTTP/1.1" 200 21844
INFO 2025-02-01 16:09:22,584 basehttp 20680 9248 "POST /api/register/ HTTP/1.1" 201 1649
ERROR 2025-02-01 16:10:21,937 log 20680 9248 Internal Server Error: /api/social-sign-in/
Traceback (most recent call last):
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\models\query.py", line 948, in get_or_create
    return self.get(**kwargs), False
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
users.models.User.DoesNotExist: User matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
sqlite3.IntegrityError: UNIQUE constraint failed: users_user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Obaidullah\Desktop\New folder (6)\Here2Dare\users\views.py", line 914, in post
    user = serializer.save()
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\rest_framework\serializers.py", line 208, in save
    self.instance = self.create(validated_data)
  File "C:\Users\Obaidullah\Desktop\New folder (6)\Here2Dare\users\serializers.py", line 273, in create
    user, created = User.objects.get_or_create(email=email, defaults={
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\models\query.py", line 955, in get_or_create
    return self.create(**params), True
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\models\query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\contrib\auth\base_user.py", line 62, in save
    super().save(*args, **kwargs)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\models\base.py", line 892, in save
    self.save_base(
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\models\base.py", line 998, in save_base
    updated = self._save_table(
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\models\base.py", line 1161, in _save_table
    results = self._do_insert(
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\models\base.py", line 1202, in _do_insert
    return manager._insert(
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\models\sql\compiler.py", line 1836, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
django.db.utils.IntegrityError: UNIQUE constraint failed: users_user.username
ERROR 2025-02-01 16:10:21,954 basehttp 20680 9248 "POST /api/social-sign-in/ HTTP/1.1" 500 26065
WARNING 2025-02-01 16:10:38,171 log 20680 9248 Bad Request: /api/register/
WARNING 2025-02-01 16:10:38,172 basehttp 20680 9248 "POST /api/register/ HTTP/1.1" 400 140
ERROR 2025-02-01 16:11:00,328 log 20680 9248 Internal Server Error: /api/register/
Traceback (most recent call last):
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
sqlite3.IntegrityError: UNIQUE constraint failed: users_user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Obaidullah\Desktop\New folder (6)\Here2Dare\users\views.py", line 778, in post
    serializer.save()
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\rest_framework\serializers.py", line 208, in save
    self.instance = self.create(validated_data)
  File "C:\Users\Obaidullah\Desktop\New folder (6)\Here2Dare\users\serializers.py", line 165, in create
    user.save()
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\contrib\auth\base_user.py", line 62, in save
    super().save(*args, **kwargs)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\models\base.py", line 892, in save
    self.save_base(
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\models\base.py", line 998, in save_base
    updated = self._save_table(
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\models\base.py", line 1161, in _save_table
    results = self._do_insert(
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\models\base.py", line 1202, in _do_insert
    return manager._insert(
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\models\sql\compiler.py", line 1836, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
django.db.utils.IntegrityError: UNIQUE constraint failed: users_user.username
ERROR 2025-02-01 16:11:00,332 basehttp 20680 9248 "POST /api/register/ HTTP/1.1" 500 24992
INFO 2025-02-01 16:17:21,567 autoreload 7088 10236 Watching for file changes with StatReloader
INFO 2025-02-01 16:17:33,707 autoreload 29496 29180 Watching for file changes with StatReloader
INFO 2025-02-01 16:17:48,217 basehttp 29496 9248 "GET / HTTP/1.1" 200 1633
INFO 2025-02-01 16:17:48,735 basehttp 29496 9248 "GET /static/drf-yasg/style.css HTTP/1.1" 200 1047
INFO 2025-02-01 16:17:48,739 basehttp 29496 9248 "GET /static/drf-yasg/swagger-ui-init.js HTTP/1.1" 200 15480
INFO 2025-02-01 16:17:48,790 basehttp 29496 28024 "GET /static/drf-yasg/swagger-ui-dist/swagger-ui.css HTTP/1.1" 200 145206
INFO 2025-02-01 16:17:48,806 basehttp 29496 20680 "GET /static/drf-yasg/insQ.min.js HTTP/1.1" 200 2093
INFO 2025-02-01 16:17:48,810 basehttp 29496 4004 "GET /static/drf-yasg/immutable.min.js HTTP/1.1" 200 56904
INFO 2025-02-01 16:17:48,811 basehttp 29496 28596 "GET /static/drf-yasg/swagger-ui-dist/swagger-ui-standalone-preset.js HTTP/1.1" 200 322863
INFO 2025-02-01 16:17:48,818 basehttp 29496 21432 "GET /static/drf-yasg/swagger-ui-dist/swagger-ui-bundle.js HTTP/1.1" 200 1046583
INFO 2025-02-01 16:17:48,941 basehttp 29496 28596 "GET /static/drf-yasg/swagger-ui-dist/favicon-32x32.png HTTP/1.1" 200 628
INFO 2025-02-01 16:17:48,980 basehttp 29496 21432 "GET /?format=openapi HTTP/1.1" 200 21844
ERROR 2025-02-01 16:18:02,216 log 29496 21432 Internal Server Error: /api/register/
Traceback (most recent call last):
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
sqlite3.IntegrityError: UNIQUE constraint failed: users_user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Obaidullah\Desktop\New folder (6)\Here2Dare\users\views.py", line 778, in post
    serializer.save()
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\rest_framework\serializers.py", line 208, in save
    self.instance = self.create(validated_data)
  File "C:\Users\Obaidullah\Desktop\New folder (6)\Here2Dare\users\serializers.py", line 165, in create
    user.save()
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\contrib\auth\base_user.py", line 62, in save
    super().save(*args, **kwargs)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\models\base.py", line 892, in save
    self.save_base(
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\models\base.py", line 998, in save_base
    updated = self._save_table(
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\models\base.py", line 1161, in _save_table
    results = self._do_insert(
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\models\base.py", line 1202, in _do_insert
    return manager._insert(
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\models\sql\compiler.py", line 1836, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
django.db.utils.IntegrityError: UNIQUE constraint failed: users_user.username
ERROR 2025-02-01 16:18:02,239 basehttp 29496 21432 "POST /api/register/ HTTP/1.1" 500 24992
INFO 2025-02-01 16:20:44,211 autoreload 23296 33236 Watching for file changes with StatReloader
WARNING 2025-02-01 16:20:58,592 log 23296 6052 Bad Request: /api/register/
WARNING 2025-02-01 16:20:58,593 basehttp 23296 6052 "POST /api/register/ HTTP/1.1" 400 53
WARNING 2025-02-01 16:21:35,008 log 23296 6052 Bad Request: /api/register/
WARNING 2025-02-01 16:21:35,009 basehttp 23296 6052 "POST /api/register/ HTTP/1.1" 400 53
INFO 2025-02-01 16:22:18,927 basehttp 23296 6052 "GET /admin/ HTTP/1.1" 302 0
INFO 2025-02-01 16:22:19,026 basehttp 23296 6052 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 3079
INFO 2025-02-01 16:22:19,051 basehttp 23296 6052 "GET /static/vendor/fontawesome-free/css/all.min.css HTTP/1.1" 304 0
INFO 2025-02-01 16:22:19,054 basehttp 23296 2424 "GET /static/vendor/adminlte/css/adminlte.min.css HTTP/1.1" 304 0
INFO 2025-02-01 16:22:19,055 basehttp 23296 31700 "GET /static/jazzmin/css/main.css HTTP/1.1" 304 0
INFO 2025-02-01 16:22:19,079 basehttp 23296 6052 "GET /static/vendor/bootstrap/js/bootstrap.min.js HTTP/1.1" 304 0
INFO 2025-02-01 16:22:19,081 basehttp 23296 2424 "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
INFO 2025-02-01 16:22:19,081 basehttp 23296 31700 "GET /static/vendor/adminlte/img/AdminLTELogo.png HTTP/1.1" 304 0
INFO 2025-02-01 16:22:19,142 basehttp 23296 31700 "GET /static/vendor/adminlte/js/adminlte.min.js HTTP/1.1" 304 0
INFO 2025-02-01 16:22:19,259 basehttp 23296 31700 "GET /static/vendor/fontawesome-free/webfonts/fa-solid-900.woff2 HTTP/1.1" 304 0
INFO 2025-02-01 16:22:24,091 basehttp 23296 31700 "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2025-02-01 16:22:24,252 basehttp 23296 31700 "GET /admin/ HTTP/1.1" 200 14016
INFO 2025-02-01 16:22:24,309 basehttp 23296 31700 "GET /static/jazzmin/js/main.js HTTP/1.1" 304 0
INFO 2025-02-01 16:22:24,354 basehttp 23296 31700 "GET /static/vendor/fontawesome-free/webfonts/fa-regular-400.woff2 HTTP/1.1" 304 0
INFO 2025-02-01 16:22:28,714 basehttp 23296 31700 "GET /admin/users/user/ HTTP/1.1" 200 23110
INFO 2025-02-01 16:22:28,751 basehttp 23296 31700 "GET /static/vendor/select2/css/select2.min.css HTTP/1.1" 304 0
INFO 2025-02-01 16:22:28,758 basehttp 23296 6052 "GET /static/jazzmin/js/change_list.js HTTP/1.1" 304 0
INFO 2025-02-01 16:22:28,770 basehttp 23296 31700 "GET /static/vendor/select2/js/select2.min.js HTTP/1.1" 304 0
INFO 2025-02-01 16:22:28,793 basehttp 23296 2424 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-01 16:24:59,634 autoreload 23296 33236 C:\Users\Obaidullah\Desktop\New folder (6)\Here2Dare\users\views.py changed, reloading.
INFO 2025-02-01 16:25:00,310 autoreload 20300 21176 Watching for file changes with StatReloader
INFO 2025-02-01 16:25:14,326 basehttp 20300 10728 "GET / HTTP/1.1" 200 1633
INFO 2025-02-01 16:25:14,824 basehttp 20300 8480 "GET /static/drf-yasg/swagger-ui-dist/swagger-ui-standalone-preset.js HTTP/1.1" 200 322863
INFO 2025-02-01 16:25:14,827 basehttp 20300 8480 "GET /static/drf-yasg/swagger-ui-init.js HTTP/1.1" 200 15480
INFO 2025-02-01 16:25:14,854 basehttp 20300 10728 "GET /static/drf-yasg/style.css HTTP/1.1" 200 1047
INFO 2025-02-01 16:25:14,879 basehttp 20300 21600 "GET /static/drf-yasg/swagger-ui-dist/swagger-ui.css HTTP/1.1" 200 145206
INFO 2025-02-01 16:25:14,887 basehttp 20300 29252 "GET /static/drf-yasg/insQ.min.js HTTP/1.1" 200 2093
INFO 2025-02-01 16:25:14,894 basehttp 20300 29220 "GET /static/drf-yasg/immutable.min.js HTTP/1.1" 200 56904
INFO 2025-02-01 16:25:14,901 basehttp 20300 8152 "GET /static/drf-yasg/swagger-ui-dist/swagger-ui-bundle.js HTTP/1.1" 200 1046583
INFO 2025-02-01 16:25:15,037 basehttp 20300 29220 "GET /static/drf-yasg/swagger-ui-dist/favicon-32x32.png HTTP/1.1" 200 628
INFO 2025-02-01 16:25:15,074 basehttp 20300 8152 "GET /?format=openapi HTTP/1.1" 200 20337
WARNING 2025-02-01 16:25:26,275 log 20300 8152 Bad Request: /api/register/
WARNING 2025-02-01 16:25:26,276 basehttp 20300 8152 "POST /api/register/ HTTP/1.1" 400 53
INFO 2025-02-01 16:37:11,036 autoreload 12300 11772 Watching for file changes with StatReloader
INFO 2025-02-01 16:37:13,532 basehttp 12300 13412 "GET / HTTP/1.1" 200 1633
INFO 2025-02-01 16:37:13,748 basehttp 12300 13412 "GET /?format=openapi HTTP/1.1" 200 20337
WARNING 2025-02-01 16:37:43,609 log 12300 13412 Bad Request: /api/register/
WARNING 2025-02-01 16:37:43,610 basehttp 12300 13412 "POST /api/register/ HTTP/1.1" 400 53
INFO 2025-02-01 16:41:07,839 autoreload 12300 11772 C:\Users\Obaidullah\Desktop\New folder (6)\Here2Dare\users\serializers.py changed, reloading.
INFO 2025-02-01 16:41:08,325 autoreload 4968 26360 Watching for file changes with StatReloader
INFO 2025-02-01 16:41:18,654 basehttp 4968 31224 "GET / HTTP/1.1" 200 1633
INFO 2025-02-01 16:41:18,793 basehttp 4968 31224 "GET /?format=openapi HTTP/1.1" 200 20337
INFO 2025-02-01 16:41:20,829 basehttp 4968 31224 "GET / HTTP/1.1" 200 1633
INFO 2025-02-01 16:41:20,993 basehttp 4968 31224 "GET /static/drf-yasg/style.css HTTP/1.1" 200 1047
INFO 2025-02-01 16:41:20,995 basehttp 4968 31224 "GET /static/drf-yasg/swagger-ui-init.js HTTP/1.1" 200 15480
INFO 2025-02-01 16:41:21,019 basehttp 4968 32200 "GET /static/drf-yasg/swagger-ui-dist/swagger-ui.css HTTP/1.1" 200 145206
INFO 2025-02-01 16:41:21,025 basehttp 4968 10476 "GET /static/drf-yasg/immutable.min.js HTTP/1.1" 200 56904
INFO 2025-02-01 16:41:21,025 basehttp 4968 23044 "GET /static/drf-yasg/insQ.min.js HTTP/1.1" 200 2093
INFO 2025-02-01 16:41:21,029 basehttp 4968 26860 "GET /static/drf-yasg/swagger-ui-dist/swagger-ui-standalone-preset.js HTTP/1.1" 200 322863
INFO 2025-02-01 16:41:21,032 basehttp 4968 22764 "GET /static/drf-yasg/swagger-ui-dist/swagger-ui-bundle.js HTTP/1.1" 200 1046583
INFO 2025-02-01 16:41:21,111 basehttp 4968 22764 "GET /?format=openapi HTTP/1.1" 200 20337
INFO 2025-02-01 16:41:21,112 basehttp 4968 26860 "GET /static/drf-yasg/swagger-ui-dist/favicon-32x32.png HTTP/1.1" 200 628
WARNING 2025-02-01 16:41:40,765 log 4968 26860 Bad Request: /api/register/
WARNING 2025-02-01 16:41:40,766 basehttp 4968 26860 "POST /api/register/ HTTP/1.1" 400 53
INFO 2025-02-01 16:51:10,071 autoreload 27980 29568 Watching for file changes with StatReloader
INFO 2025-02-01 16:52:37,250 autoreload 27980 29568 C:\Users\Obaidullah\Desktop\New folder (6)\Here2Dare\users\serializers.py changed, reloading.
INFO 2025-02-01 16:52:37,799 autoreload 31860 33012 Watching for file changes with StatReloader
INFO 2025-02-01 16:54:27,926 autoreload 31860 33012 C:\Users\Obaidullah\Desktop\New folder (6)\Here2Dare\users\views.py changed, reloading.
INFO 2025-02-01 16:54:28,565 autoreload 17600 33108 Watching for file changes with StatReloader
INFO 2025-02-01 16:54:32,376 basehttp 17600 13692 "GET / HTTP/1.1" 200 1633
ERROR 2025-02-01 16:54:32,741 log 17600 13692 Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\views.py", line 96, in get
    schema = generator.get_schema(request, self.public)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\generators.py", line 276, in get_schema
    paths, prefix = self.get_paths(endpoints, components, request, public)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\generators.py", line 482, in get_paths
    operation = self.get_operation(view, path, prefix, method, components, request)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\generators.py", line 524, in get_operation
    operation = view_inspector.get_operation(operation_keys)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\inspectors\view.py", line 32, in get_operation
    body = self.get_request_body_parameters(consumes)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\inspectors\view.py", line 85, in get_request_body_parameters
    schema = self.get_request_body_schema(serializer)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\inspectors\view.py", line 142, in get_request_body_schema
    return self.serializer_to_schema(serializer)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\inspectors\base.py", line 438, in serializer_to_schema
    return self.probe_inspectors(
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\inspectors\base.py", line 110, in probe_inspectors
    result = method(obj, **kwargs)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\inspectors\field.py", line 42, in get_schema
    return self.probe_field_inspectors(serializer, openapi.Schema, self.use_definitions)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\inspectors\base.py", line 228, in probe_field_inspectors
    return self.probe_inspectors(
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\inspectors\base.py", line 110, in probe_inspectors
    result = method(obj, **kwargs)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\inspectors\field.py", line 133, in field_to_swagger_object
    actual_schema = definitions.setdefault(ref_name, make_schema_definition)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\openapi.py", line 685, in setdefault
    ret = maker()
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\inspectors\field.py", line 102, in make_schema_definition
    for property_name, child in serializer.fields.items():
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\rest_framework\serializers.py", line 372, in fields
    for key, value in self.get_fields().items():
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\rest_framework\serializers.py", line 1103, in get_fields
    field_class, field_kwargs = self.build_field(
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\rest_framework\serializers.py", line 1249, in build_field
    return self.build_unknown_field(field_name, model_class)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\rest_framework\serializers.py", line 1367, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `full_name` is not valid for model `User` in `users.serializers.UserProfileSerializerv2`.
ERROR 2025-02-01 16:54:32,748 basehttp 17600 13692 "GET /?format=openapi HTTP/1.1" 500 222141
INFO 2025-02-01 16:54:52,021 autoreload 17600 33108 C:\Users\Obaidullah\Desktop\New folder (6)\Here2Dare\users\views.py changed, reloading.
INFO 2025-02-01 16:54:52,573 autoreload 2016 18748 Watching for file changes with StatReloader
INFO 2025-02-01 16:54:57,211 basehttp 2016 8380 "GET / HTTP/1.1" 200 1633
INFO 2025-02-01 16:54:57,356 basehttp 2016 8380 "GET /static/drf-yasg/style.css HTTP/1.1" 200 1047
INFO 2025-02-01 16:54:57,359 basehttp 2016 8380 "GET /static/drf-yasg/swagger-ui-init.js HTTP/1.1" 200 15480
INFO 2025-02-01 16:54:57,387 basehttp 2016 20440 "GET /static/drf-yasg/swagger-ui-dist/swagger-ui.css HTTP/1.1" 200 145206
INFO 2025-02-01 16:54:57,394 basehttp 2016 2792 "GET /static/drf-yasg/insQ.min.js HTTP/1.1" 200 2093
INFO 2025-02-01 16:54:57,397 basehttp 2016 24096 "GET /static/drf-yasg/immutable.min.js HTTP/1.1" 200 56904
INFO 2025-02-01 16:54:57,404 basehttp 2016 32028 "GET /static/drf-yasg/swagger-ui-dist/swagger-ui-standalone-preset.js HTTP/1.1" 200 322863
INFO 2025-02-01 16:54:57,413 basehttp 2016 7220 "GET /static/drf-yasg/swagger-ui-dist/swagger-ui-bundle.js HTTP/1.1" 200 1046583
INFO 2025-02-01 16:54:57,471 basehttp 2016 32028 "GET /static/drf-yasg/swagger-ui-dist/favicon-32x32.png HTTP/1.1" 200 628
ERROR 2025-02-01 16:54:57,535 log 2016 7220 Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\views.py", line 96, in get
    schema = generator.get_schema(request, self.public)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\generators.py", line 276, in get_schema
    paths, prefix = self.get_paths(endpoints, components, request, public)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\generators.py", line 482, in get_paths
    operation = self.get_operation(view, path, prefix, method, components, request)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\generators.py", line 524, in get_operation
    operation = view_inspector.get_operation(operation_keys)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\inspectors\view.py", line 32, in get_operation
    body = self.get_request_body_parameters(consumes)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\inspectors\view.py", line 85, in get_request_body_parameters
    schema = self.get_request_body_schema(serializer)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\inspectors\view.py", line 142, in get_request_body_schema
    return self.serializer_to_schema(serializer)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\inspectors\base.py", line 438, in serializer_to_schema
    return self.probe_inspectors(
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\inspectors\base.py", line 110, in probe_inspectors
    result = method(obj, **kwargs)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\inspectors\field.py", line 42, in get_schema
    return self.probe_field_inspectors(serializer, openapi.Schema, self.use_definitions)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\inspectors\base.py", line 228, in probe_field_inspectors
    return self.probe_inspectors(
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\inspectors\base.py", line 110, in probe_inspectors
    result = method(obj, **kwargs)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\inspectors\field.py", line 133, in field_to_swagger_object
    actual_schema = definitions.setdefault(ref_name, make_schema_definition)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\openapi.py", line 685, in setdefault
    ret = maker()
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\inspectors\field.py", line 102, in make_schema_definition
    for property_name, child in serializer.fields.items():
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\rest_framework\serializers.py", line 372, in fields
    for key, value in self.get_fields().items():
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\rest_framework\serializers.py", line 1103, in get_fields
    field_class, field_kwargs = self.build_field(
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\rest_framework\serializers.py", line 1249, in build_field
    return self.build_unknown_field(field_name, model_class)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\rest_framework\serializers.py", line 1367, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `full_name` is not valid for model `User` in `users.serializers.UserProfileSerializerv2`.
ERROR 2025-02-01 16:54:57,540 basehttp 2016 7220 "GET /?format=openapi HTTP/1.1" 500 222406
INFO 2025-02-01 16:55:18,605 autoreload 2016 18748 C:\Users\Obaidullah\Desktop\New folder (6)\Here2Dare\users\views.py changed, reloading.
INFO 2025-02-01 16:55:19,109 autoreload 5880 24016 Watching for file changes with StatReloader
INFO 2025-02-01 16:55:27,883 basehttp 5880 23880 "GET / HTTP/1.1" 200 1633
INFO 2025-02-01 16:55:28,054 basehttp 5880 23880 "GET /static/drf-yasg/style.css HTTP/1.1" 200 1047
INFO 2025-02-01 16:55:28,056 basehttp 5880 23880 "GET /static/drf-yasg/swagger-ui-init.js HTTP/1.1" 200 15480
INFO 2025-02-01 16:55:28,068 basehttp 5880 32416 "GET /static/drf-yasg/swagger-ui-dist/swagger-ui.css HTTP/1.1" 200 145206
INFO 2025-02-01 16:55:28,073 basehttp 5880 16204 "GET /static/drf-yasg/immutable.min.js HTTP/1.1" 200 56904
INFO 2025-02-01 16:55:28,077 basehttp 5880 24864 "GET /static/drf-yasg/insQ.min.js HTTP/1.1" 200 2093
INFO 2025-02-01 16:55:28,084 basehttp 5880 33112 "GET /static/drf-yasg/swagger-ui-dist/swagger-ui-standalone-preset.js HTTP/1.1" 200 322863
INFO 2025-02-01 16:55:28,093 basehttp 5880 15216 "GET /static/drf-yasg/swagger-ui-dist/swagger-ui-bundle.js HTTP/1.1" 200 1046583
INFO 2025-02-01 16:55:28,165 basehttp 5880 33112 "GET /static/drf-yasg/swagger-ui-dist/favicon-32x32.png HTTP/1.1" 200 628
ERROR 2025-02-01 16:55:28,222 log 5880 15216 Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\views.py", line 96, in get
    schema = generator.get_schema(request, self.public)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\generators.py", line 276, in get_schema
    paths, prefix = self.get_paths(endpoints, components, request, public)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\generators.py", line 482, in get_paths
    operation = self.get_operation(view, path, prefix, method, components, request)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\generators.py", line 524, in get_operation
    operation = view_inspector.get_operation(operation_keys)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\inspectors\view.py", line 32, in get_operation
    body = self.get_request_body_parameters(consumes)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\inspectors\view.py", line 85, in get_request_body_parameters
    schema = self.get_request_body_schema(serializer)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\inspectors\view.py", line 142, in get_request_body_schema
    return self.serializer_to_schema(serializer)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\inspectors\base.py", line 438, in serializer_to_schema
    return self.probe_inspectors(
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\inspectors\base.py", line 110, in probe_inspectors
    result = method(obj, **kwargs)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\inspectors\field.py", line 42, in get_schema
    return self.probe_field_inspectors(serializer, openapi.Schema, self.use_definitions)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\inspectors\base.py", line 228, in probe_field_inspectors
    return self.probe_inspectors(
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\inspectors\base.py", line 110, in probe_inspectors
    result = method(obj, **kwargs)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\inspectors\field.py", line 133, in field_to_swagger_object
    actual_schema = definitions.setdefault(ref_name, make_schema_definition)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\openapi.py", line 685, in setdefault
    ret = maker()
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\inspectors\field.py", line 102, in make_schema_definition
    for property_name, child in serializer.fields.items():
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\rest_framework\serializers.py", line 372, in fields
    for key, value in self.get_fields().items():
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\rest_framework\serializers.py", line 1103, in get_fields
    field_class, field_kwargs = self.build_field(
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\rest_framework\serializers.py", line 1249, in build_field
    return self.build_unknown_field(field_name, model_class)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\rest_framework\serializers.py", line 1367, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `full_name` is not valid for model `User` in `users.serializers.UserProfileSerializerv2`.
ERROR 2025-02-01 16:55:28,226 basehttp 5880 15216 "GET /?format=openapi HTTP/1.1" 500 223266
INFO 2025-02-01 16:56:51,366 autoreload 5880 24016 C:\Users\Obaidullah\Desktop\New folder (6)\Here2Dare\users\serializers.py changed, reloading.
INFO 2025-02-01 16:56:51,938 autoreload 12228 23376 Watching for file changes with StatReloader
INFO 2025-02-01 16:56:55,531 basehttp 12228 6224 "GET / HTTP/1.1" 200 1633
ERROR 2025-02-01 16:56:55,810 log 12228 6224 Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\views.py", line 96, in get
    schema = generator.get_schema(request, self.public)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\generators.py", line 276, in get_schema
    paths, prefix = self.get_paths(endpoints, components, request, public)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\generators.py", line 482, in get_paths
    operation = self.get_operation(view, path, prefix, method, components, request)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\generators.py", line 524, in get_operation
    operation = view_inspector.get_operation(operation_keys)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\inspectors\view.py", line 32, in get_operation
    body = self.get_request_body_parameters(consumes)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\inspectors\view.py", line 85, in get_request_body_parameters
    schema = self.get_request_body_schema(serializer)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\inspectors\view.py", line 142, in get_request_body_schema
    return self.serializer_to_schema(serializer)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\inspectors\base.py", line 438, in serializer_to_schema
    return self.probe_inspectors(
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\inspectors\base.py", line 110, in probe_inspectors
    result = method(obj, **kwargs)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\inspectors\field.py", line 42, in get_schema
    return self.probe_field_inspectors(serializer, openapi.Schema, self.use_definitions)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\inspectors\base.py", line 228, in probe_field_inspectors
    return self.probe_inspectors(
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\inspectors\base.py", line 110, in probe_inspectors
    result = method(obj, **kwargs)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\inspectors\field.py", line 133, in field_to_swagger_object
    actual_schema = definitions.setdefault(ref_name, make_schema_definition)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\openapi.py", line 685, in setdefault
    ret = maker()
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\inspectors\field.py", line 102, in make_schema_definition
    for property_name, child in serializer.fields.items():
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\rest_framework\serializers.py", line 372, in fields
    for key, value in self.get_fields().items():
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\rest_framework\serializers.py", line 1103, in get_fields
    field_class, field_kwargs = self.build_field(
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\rest_framework\serializers.py", line 1249, in build_field
    return self.build_unknown_field(field_name, model_class)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\rest_framework\serializers.py", line 1367, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `full_name` is not valid for model `User` in `users.serializers.UserProfileSerializerv2`.
ERROR 2025-02-01 16:56:55,815 basehttp 12228 6224 "GET /?format=openapi HTTP/1.1" 500 222141
INFO 2025-02-01 16:58:24,486 autoreload 12228 23376 C:\Users\Obaidullah\Desktop\New folder (6)\Here2Dare\users\models.py changed, reloading.
INFO 2025-02-01 16:58:24,980 autoreload 28048 29744 Watching for file changes with StatReloader
INFO 2025-02-01 16:58:31,786 basehttp 28048 10060 "GET / HTTP/1.1" 200 1633
INFO 2025-02-01 16:58:31,936 basehttp 28048 10060 "GET /static/drf-yasg/style.css HTTP/1.1" 200 1047
INFO 2025-02-01 16:58:31,938 basehttp 28048 10060 "GET /static/drf-yasg/swagger-ui-init.js HTTP/1.1" 200 15480
INFO 2025-02-01 16:58:31,961 basehttp 28048 14868 "GET /static/drf-yasg/immutable.min.js HTTP/1.1" 200 56904
INFO 2025-02-01 16:58:31,964 basehttp 28048 23704 "GET /static/drf-yasg/swagger-ui-dist/swagger-ui.css HTTP/1.1" 200 145206
INFO 2025-02-01 16:58:31,968 basehttp 28048 23116 "GET /static/drf-yasg/insQ.min.js HTTP/1.1" 200 2093
INFO 2025-02-01 16:58:31,972 basehttp 28048 20276 "GET /static/drf-yasg/swagger-ui-dist/swagger-ui-standalone-preset.js HTTP/1.1" 200 322863
INFO 2025-02-01 16:58:31,976 basehttp 28048 20188 "GET /static/drf-yasg/swagger-ui-dist/swagger-ui-bundle.js HTTP/1.1" 200 1046583
INFO 2025-02-01 16:58:32,049 basehttp 28048 20276 "GET /static/drf-yasg/swagger-ui-dist/favicon-32x32.png HTTP/1.1" 200 628
ERROR 2025-02-01 16:58:32,109 log 28048 20188 Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\views.py", line 96, in get
    schema = generator.get_schema(request, self.public)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\generators.py", line 276, in get_schema
    paths, prefix = self.get_paths(endpoints, components, request, public)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\generators.py", line 482, in get_paths
    operation = self.get_operation(view, path, prefix, method, components, request)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\generators.py", line 524, in get_operation
    operation = view_inspector.get_operation(operation_keys)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\inspectors\view.py", line 32, in get_operation
    body = self.get_request_body_parameters(consumes)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\inspectors\view.py", line 85, in get_request_body_parameters
    schema = self.get_request_body_schema(serializer)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\inspectors\view.py", line 142, in get_request_body_schema
    return self.serializer_to_schema(serializer)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\inspectors\base.py", line 438, in serializer_to_schema
    return self.probe_inspectors(
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\inspectors\base.py", line 110, in probe_inspectors
    result = method(obj, **kwargs)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\inspectors\field.py", line 42, in get_schema
    return self.probe_field_inspectors(serializer, openapi.Schema, self.use_definitions)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\inspectors\base.py", line 228, in probe_field_inspectors
    return self.probe_inspectors(
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\inspectors\base.py", line 110, in probe_inspectors
    result = method(obj, **kwargs)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\inspectors\field.py", line 133, in field_to_swagger_object
    actual_schema = definitions.setdefault(ref_name, make_schema_definition)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\openapi.py", line 685, in setdefault
    ret = maker()
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\drf_yasg\inspectors\field.py", line 102, in make_schema_definition
    for property_name, child in serializer.fields.items():
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\rest_framework\serializers.py", line 372, in fields
    for key, value in self.get_fields().items():
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\rest_framework\serializers.py", line 1103, in get_fields
    field_class, field_kwargs = self.build_field(
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\rest_framework\serializers.py", line 1249, in build_field
    return self.build_unknown_field(field_name, model_class)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\rest_framework\serializers.py", line 1367, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `full_name` is not valid for model `User` in `users.serializers.UserProfileSerializerv2`.
ERROR 2025-02-01 16:58:32,113 basehttp 28048 20188 "GET /?format=openapi HTTP/1.1" 500 222406
INFO 2025-02-01 16:59:07,514 autoreload 28048 29744 C:\Users\Obaidullah\Desktop\New folder (6)\Here2Dare\users\models.py changed, reloading.
INFO 2025-02-01 16:59:07,997 autoreload 17040 31328 Watching for file changes with StatReloader
INFO 2025-02-01 16:59:37,778 autoreload 28632 26292 Watching for file changes with StatReloader
INFO 2025-02-01 16:59:42,098 basehttp 28632 22936 "GET / HTTP/1.1" 200 1633
INFO 2025-02-01 16:59:42,318 basehttp 28632 22936 "GET /?format=openapi HTTP/1.1" 200 20326
INFO 2025-02-01 17:00:03,955 basehttp 28632 22936 "POST /api/register/ HTTP/1.1" 201 1639
WARNING 2025-02-01 17:00:12,311 log 28632 22936 Bad Request: /api/register/
WARNING 2025-02-01 17:00:12,312 basehttp 28632 22936 "POST /api/register/ HTTP/1.1" 400 140
INFO 2025-02-01 17:00:39,626 basehttp 28632 22936 "POST /api/register/ HTTP/1.1" 201 1653
WARNING 2025-02-01 17:19:20,577 log 28632 28248 Unauthorized: /api/upload-doc/
WARNING 2025-02-01 17:19:20,578 basehttp 28632 28248 "POST /api/upload-doc/ HTTP/1.1" 401 51
INFO 2025-02-01 17:20:11,406 basehttp 28632 28248 "GET /admin/ HTTP/1.1" 200 14016
ERROR 2025-02-01 17:20:16,327 log 28632 28248 Internal Server Error: /admin/file_storage/uploadedfile/
Traceback (most recent call last):
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such table: file_storage_uploadedfile

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\contrib\admin\options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\contrib\admin\sites.py", line 241, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\contrib\admin\options.py", line 2001, in changelist_view
    cl = self.get_changelist_instance(request)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\contrib\admin\options.py", line 866, in get_changelist_instance
    return ChangeList(
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\contrib\admin\views\main.py", line 146, in __init__
    self.get_results(request)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\contrib\admin\views\main.py", line 313, in get_results
    result_count = paginator.count
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\core\paginator.py", line 110, in count
    return c()
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\models\query.py", line 620, in count
    return self.query.get_count(using=self.db)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\models\sql\query.py", line 630, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\models\sql\query.py", line 616, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Obaidullah\AppData\Roaming\Python\Python310-32\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such table: file_storage_uploadedfile
ERROR 2025-02-01 17:20:16,339 basehttp 28632 28248 "GET /admin/file_storage/uploadedfile/ HTTP/1.1" 500 196369
WARNING 2025-02-01 17:20:16,467 log 28632 28248 Not Found: /favicon.ico
WARNING 2025-02-01 17:20:16,469 basehttp 28632 28248 "GET /favicon.ico HTTP/1.1" 404 3200
INFO 2025-02-01 17:20:44,218 autoreload 33308 31372 Watching for file changes with StatReloader
INFO 2025-02-01 17:20:48,913 basehttp 33308 33588 "GET /admin/file_storage/uploadedfile/ HTTP/1.1" 200 12464
INFO 2025-02-01 17:20:48,948 basehttp 33308 21036 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-01 17:20:49,075 basehttp 33308 33588 "GET /static/vendor/fontawesome-free/css/all.min.css HTTP/1.1" 200 103009
INFO 2025-02-01 17:20:49,099 basehttp 33308 33588 "GET /static/admin/js/core.js HTTP/1.1" 200 6208
INFO 2025-02-01 17:20:49,104 basehttp 33308 24348 "GET /static/vendor/select2/css/select2.min.css HTTP/1.1" 200 16264
INFO 2025-02-01 17:20:49,118 basehttp 33308 14832 "GET /static/jazzmin/css/main.css HTTP/1.1" 200 16969
INFO 2025-02-01 17:20:49,125 basehttp 33308 21036 "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
INFO 2025-02-01 17:20:49,130 basehttp 33308 33588 "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 9097
INFO 2025-02-01 17:20:49,132 basehttp 33308 16152 "GET /static/vendor/adminlte/css/adminlte.min.css HTTP/1.1" 200 1382975
INFO 2025-02-01 17:20:49,138 basehttp 33308 33588 "GET /static/vendor/adminlte/img/AdminLTELogo.png HTTP/1.1" 200 2637
INFO 2025-02-01 17:20:49,138 basehttp 33308 24348 "GET /static/admin/js/actions.js HTTP/1.1" 200 8076
INFO 2025-02-01 17:20:49,141 basehttp 33308 14832 "GET /static/admin/js/urlify.js HTTP/1.1" 200 7887
INFO 2025-02-01 17:20:49,148 basehttp 33308 21036 "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
INFO 2025-02-01 17:20:49,186 basehttp 33308 33588 "GET /static/vendor/bootstrap/js/bootstrap.min.js HTTP/1.1" 200 62440
INFO 2025-02-01 17:20:49,187 basehttp 33308 21036 "GET /static/vendor/adminlte/js/adminlte.min.js HTTP/1.1" 200 44244
INFO 2025-02-01 17:20:49,190 basehttp 33308 9128 "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 285314
INFO 2025-02-01 17:20:49,209 basehttp 33308 21036 "GET /static/jazzmin/js/main.js HTTP/1.1" 200 2391
INFO 2025-02-01 17:20:49,214 basehttp 33308 21036 "GET /static/jazzmin/js/change_list.js HTTP/1.1" 200 2252
INFO 2025-02-01 17:20:49,218 basehttp 33308 16152 "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 325171
INFO 2025-02-01 17:20:49,230 basehttp 33308 33588 "GET /static/vendor/select2/js/select2.min.js HTTP/1.1" 200 73170
INFO 2025-02-01 17:20:49,409 basehttp 33308 33588 "GET /static/vendor/fontawesome-free/webfonts/fa-solid-900.woff2 HTTP/1.1" 200 156400
INFO 2025-02-01 17:20:49,412 basehttp 33308 16152 "GET /static/vendor/fontawesome-free/webfonts/fa-regular-400.woff2 HTTP/1.1" 200 25392
INFO 2025-02-01 17:20:51,947 basehttp 33308 16152 "GET /admin/users/documentverification/ HTTP/1.1" 200 13356
INFO 2025-02-01 17:20:51,984 basehttp 33308 16152 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-01 17:20:54,578 basehttp 33308 16152 "GET /admin/ HTTP/1.1" 200 14016
INFO 2025-02-01 17:21:07,441 basehttp 33308 16152 "GET / HTTP/1.1" 200 1633
INFO 2025-02-01 17:21:07,465 basehttp 33308 16152 "GET /static/drf-yasg/style.css HTTP/1.1" 200 1047
INFO 2025-02-01 17:21:07,485 basehttp 33308 14832 "GET /static/drf-yasg/insQ.min.js HTTP/1.1" 200 2093
INFO 2025-02-01 17:21:07,488 basehttp 33308 16152 "GET /static/drf-yasg/swagger-ui-init.js HTTP/1.1" 200 15480
INFO 2025-02-01 17:21:07,490 basehttp 33308 24348 "GET /static/drf-yasg/immutable.min.js HTTP/1.1" 200 56904
INFO 2025-02-01 17:21:07,495 basehttp 33308 33588 "GET /static/drf-yasg/swagger-ui-dist/swagger-ui.css HTTP/1.1" 200 145206
INFO 2025-02-01 17:21:07,504 basehttp 33308 9128 "GET /static/drf-yasg/swagger-ui-dist/swagger-ui-standalone-preset.js HTTP/1.1" 200 322863
INFO 2025-02-01 17:21:07,510 basehttp 33308 21036 "GET /static/drf-yasg/swagger-ui-dist/swagger-ui-bundle.js HTTP/1.1" 200 1046583
INFO 2025-02-01 17:21:07,597 basehttp 33308 9128 "GET /static/drf-yasg/swagger-ui-dist/favicon-32x32.png HTTP/1.1" 200 628
INFO 2025-02-01 17:21:07,622 basehttp 33308 21036 "GET /?format=openapi HTTP/1.1" 200 20326
INFO 2025-02-01 17:21:18,357 basehttp 33308 21036 "GET /admin/users/user/ HTTP/1.1" 200 24227
INFO 2025-02-01 17:21:18,397 basehttp 33308 21036 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
WARNING 2025-02-01 17:21:50,083 log 33308 21036 Unauthorized: /api/login/
WARNING 2025-02-01 17:21:50,084 basehttp 33308 21036 "POST /api/login/ HTTP/1.1" 401 75
INFO 2025-02-01 17:22:01,865 basehttp 33308 21036 "POST /api/login/ HTTP/1.1" 200 1647
INFO 2025-02-01 17:22:57,274 basehttp 33308 21036 "POST /api/upload-doc/ HTTP/1.1" 200 1290
INFO 2025-02-01 17:23:37,645 basehttp 33308 21036 "GET /api/getuserprofile/ HTTP/1.1" 200 1394
INFO 2025-02-01 17:36:22,491 autoreload 9200 33312 Watching for file changes with StatReloader
INFO 2025-02-01 17:36:31,002 basehttp 9200 3000 "GET / HTTP/1.1" 200 1633
INFO 2025-02-01 17:36:31,233 basehttp 9200 3000 "GET /?format=openapi HTTP/1.1" 200 20326
INFO 2025-02-01 17:37:31,932 basehttp 9200 3000 "GET /api/getfileurl/ HTTP/1.1" 200 65
INFO 2025-02-01 17:38:24,984 basehttp 9200 3000 "GET / HTTP/1.1" 200 1633
INFO 2025-02-01 17:38:25,141 basehttp 9200 3000 "GET /?format=openapi HTTP/1.1" 200 20326
INFO 2025-02-01 17:38:31,566 basehttp 9200 3000 "GET /admin/file_storage/uploadedfile/ HTTP/1.1" 200 12464
INFO 2025-02-01 17:38:31,616 basehttp 9200 3000 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-01 17:38:32,890 basehttp 9200 3000 "GET /admin/file_storage/uploadedfile/ HTTP/1.1" 200 12464
INFO 2025-02-01 17:38:32,923 basehttp 9200 3000 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-01 17:39:57,972 basehttp 9200 3000 "POST /api/create_file_url/ HTTP/1.1" 201 123
INFO 2025-02-01 17:40:11,205 basehttp 9200 3000 "GET /api/getfileurl/ HTTP/1.1" 200 170
INFO 2025-02-01 17:40:48,057 basehttp 9200 3000 "POST /api/social-sign-in/ HTTP/1.1" 200 707
WARNING 2025-02-01 17:41:32,336 log 9200 3000 Bad Request: /api/social-sign-in/
WARNING 2025-02-01 17:41:32,337 basehttp 9200 3000 "POST /api/social-sign-in/ HTTP/1.1" 400 117
WARNING 2025-02-01 17:41:38,349 log 9200 3000 Bad Request: /api/social-sign-in/
WARNING 2025-02-01 17:41:38,350 basehttp 9200 3000 "POST /api/social-sign-in/ HTTP/1.1" 400 117
INFO 2025-02-01 17:45:18,887 autoreload 9200 33312 C:\Users\Obaidullah\Desktop\New folder (6)\Here2Dare\H2D\settings.py changed, reloading.
INFO 2025-02-01 17:45:19,562 autoreload 22680 27900 Watching for file changes with StatReloader
